/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpi.emsp.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ActiveChargingProfile
 */
@JsonPropertyOrder({
        ActiveChargingProfile.JSON_PROPERTY_START_DATE_TIME,
        ActiveChargingProfile.JSON_PROPERTY_CHARGING_PROFILE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-22T18:56:56.429779+02:00[Europe/Kiev]")
public class ActiveChargingProfile {
    public static final String JSON_PROPERTY_START_DATE_TIME = "start_date_time";
    public static final String JSON_PROPERTY_CHARGING_PROFILE = "charging_profile";
    private OffsetDateTime startDateTime;
    private ChargingProfile chargingProfile;

    public ActiveChargingProfile() {
    }

    public ActiveChargingProfile startDateTime(OffsetDateTime startDateTime) {

        this.startDateTime = startDateTime;
        return this;
    }

   /**
   * Get startDateTime
   * @return startDateTime
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getStartDateTime() {
    return startDateTime;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }


    public ActiveChargingProfile chargingProfile(ChargingProfile chargingProfile) {

        this.chargingProfile = chargingProfile;
        return this;
    }

   /**
   * Get chargingProfile
   * @return chargingProfile
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHARGING_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChargingProfile getChargingProfile() {
    return chargingProfile;
  }


  @JsonProperty(JSON_PROPERTY_CHARGING_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChargingProfile(ChargingProfile chargingProfile) {
    this.chargingProfile = chargingProfile;
  }

  @Override
  public boolean equals(Object o) {
      if (this == o) {
          return true;
      }
      if (o == null || getClass() != o.getClass()) {
          return false;
      }
      ActiveChargingProfile activeChargingProfile = (ActiveChargingProfile) o;
      return Objects.equals(this.startDateTime, activeChargingProfile.startDateTime) &&
              Objects.equals(this.chargingProfile, activeChargingProfile.chargingProfile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDateTime, chargingProfile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
      sb.append("class ActiveChargingProfile {\n");
      sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    chargingProfile: ").append(toIndentedString(chargingProfile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

