/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpi.emsp.client.model;

import com.fasterxml.jackson.annotation.*;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TariffDto
 */
@JsonPropertyOrder({
        TariffDto.JSON_PROPERTY_ID,
        TariffDto.JSON_PROPERTY_CURRENCY,
        TariffDto.JSON_PROPERTY_TYPE,
        TariffDto.JSON_PROPERTY_ELEMENTS,
        TariffDto.JSON_PROPERTY_COUNTRY_CODE,
        TariffDto.JSON_PROPERTY_PARTY_ID,
        TariffDto.JSON_PROPERTY_LAST_UPDATED,
        TariffDto.JSON_PROPERTY_TARIFF_ALT_TEXT,
        TariffDto.JSON_PROPERTY_TARIFF_ALT_URL,
        TariffDto.JSON_PROPERTY_MIN_PRICE,
        TariffDto.JSON_PROPERTY_MAX_PRICE,
        TariffDto.JSON_PROPERTY_START_DATE_TIME,
        TariffDto.JSON_PROPERTY_END_DATE_TIME,
        TariffDto.JSON_PROPERTY_ENERGY_MIX
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-22T18:56:56.429779+02:00[Europe/Kiev]")
public class TariffDto {
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_CURRENCY = "currency";
    public static final String JSON_PROPERTY_ELEMENTS = "elements";
    public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
    public static final String JSON_PROPERTY_PARTY_ID = "party_id";

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;
    public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
    public static final String JSON_PROPERTY_TARIFF_ALT_TEXT = "tariff_alt_text";
    public static final String JSON_PROPERTY_TARIFF_ALT_URL = "tariff_alt_url";
    public static final String JSON_PROPERTY_MIN_PRICE = "min_price";
    private String id;
    private String currency;
    private List<TariffElement> elements = new ArrayList<>();
    private String countryCode;
    private String partyId;
    private OffsetDateTime lastUpdated;
    private List<DisplayText> tariffAltText;
    private String tariffAltUrl;
    private Price minPrice;
    public TariffDto() {
  }

  public static final String JSON_PROPERTY_MAX_PRICE = "max_price";
  private Price maxPrice;

  public static final String JSON_PROPERTY_START_DATE_TIME = "start_date_time";
  private OffsetDateTime startDateTime;

  public static final String JSON_PROPERTY_END_DATE_TIME = "end_date_time";
  private OffsetDateTime endDateTime;

  public static final String JSON_PROPERTY_ENERGY_MIX = "energy_mix";
  private EnergyMix energyMix;

    public TariffDto id(String id) {

        this.id = id;
        return this;
  }

    public TariffDto currency(String currency) {

        this.currency = currency;
        return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }

    public TariffDto type(TypeEnum type) {

        this.type = type;
        return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }

    public TariffDto elements(List<TariffElement> elements) {

        this.elements = elements;
        return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }

    public TariffDto addElementsItem(TariffElement elementsItem) {
        if (this.elements == null) {
            this.elements = new ArrayList<>();
        }
        this.elements.add(elementsItem);
        return this;
  }

    public TariffDto countryCode(String countryCode) {

        this.countryCode = countryCode;
        return this;
  }

   /**
   * Get elements
   * @return elements
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TariffElement> getElements() {
    return elements;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setElements(List<TariffElement> elements) {
    this.elements = elements;
  }

    public TariffDto partyId(String partyId) {

        this.partyId = partyId;
        return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

    @JsonProperty(JSON_PROPERTY_PARTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

   /**
   * Get partyId
   * @return partyId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPartyId() {
    return partyId;
  }

    public TariffDto lastUpdated(OffsetDateTime lastUpdated) {

        this.lastUpdated = lastUpdated;
        return this;
    }

    /**
     * Get lastUpdated
     *
     * @return lastUpdated
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public OffsetDateTime getLastUpdated() {
        return lastUpdated;
    }

    @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLastUpdated(OffsetDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public TariffDto tariffAltText(List<DisplayText> tariffAltText) {

        this.tariffAltText = tariffAltText;
        return this;
    }

    public TariffDto addTariffAltTextItem(DisplayText tariffAltTextItem) {
        if (this.tariffAltText == null) {
            this.tariffAltText = new ArrayList<>();
        }
        this.tariffAltText.add(tariffAltTextItem);
        return this;
  }

    public TariffDto tariffAltUrl(String tariffAltUrl) {

        this.tariffAltUrl = tariffAltUrl;
        return this;
  }

   /**
   * Get tariffAltText
   * @return tariffAltText
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARIFF_ALT_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DisplayText> getTariffAltText() {
    return tariffAltText;
  }


  @JsonProperty(JSON_PROPERTY_TARIFF_ALT_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTariffAltText(List<DisplayText> tariffAltText) {
    this.tariffAltText = tariffAltText;
  }

    public TariffDto minPrice(Price minPrice) {

        this.minPrice = minPrice;
        return this;
  }

   /**
   * Get tariffAltUrl
   * @return tariffAltUrl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARIFF_ALT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTariffAltUrl() {
    return tariffAltUrl;
  }


  @JsonProperty(JSON_PROPERTY_TARIFF_ALT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTariffAltUrl(String tariffAltUrl) {
    this.tariffAltUrl = tariffAltUrl;
  }

    public TariffDto maxPrice(Price maxPrice) {

        this.maxPrice = maxPrice;
        return this;
  }

   /**
   * Get minPrice
   * @return minPrice
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Price getMinPrice() {
    return minPrice;
  }


  @JsonProperty(JSON_PROPERTY_MIN_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinPrice(Price minPrice) {
    this.minPrice = minPrice;
  }

    public TariffDto startDateTime(OffsetDateTime startDateTime) {

        this.startDateTime = startDateTime;
        return this;
  }

   /**
   * Get maxPrice
   * @return maxPrice
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Price getMaxPrice() {
    return maxPrice;
  }


  @JsonProperty(JSON_PROPERTY_MAX_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxPrice(Price maxPrice) {
    this.maxPrice = maxPrice;
  }

    public TariffDto endDateTime(OffsetDateTime endDateTime) {

        this.endDateTime = endDateTime;
        return this;
  }

   /**
   * Get startDateTime
   * @return startDateTime
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartDateTime() {
    return startDateTime;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }

    public TariffDto energyMix(EnergyMix energyMix) {

        this.energyMix = energyMix;
        return this;
  }

   /**
   * Get endDateTime
   * @return endDateTime
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndDateTime() {
    return endDateTime;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDateTime(OffsetDateTime endDateTime) {
    this.endDateTime = endDateTime;
  }

  @Override
  public boolean equals(Object o) {
      if (this == o) {
          return true;
      }
      if (o == null || getClass() != o.getClass()) {
          return false;
      }
      TariffDto tariffDto = (TariffDto) o;
      return Objects.equals(this.id, tariffDto.id) &&
              Objects.equals(this.currency, tariffDto.currency) &&
              Objects.equals(this.type, tariffDto.type) &&
              Objects.equals(this.elements, tariffDto.elements) &&
              Objects.equals(this.countryCode, tariffDto.countryCode) &&
              Objects.equals(this.partyId, tariffDto.partyId) &&
              Objects.equals(this.lastUpdated, tariffDto.lastUpdated) &&
              Objects.equals(this.tariffAltText, tariffDto.tariffAltText) &&
              Objects.equals(this.tariffAltUrl, tariffDto.tariffAltUrl) &&
              Objects.equals(this.minPrice, tariffDto.minPrice) &&
              Objects.equals(this.maxPrice, tariffDto.maxPrice) &&
              Objects.equals(this.startDateTime, tariffDto.startDateTime) &&
              Objects.equals(this.endDateTime, tariffDto.endDateTime) &&
              Objects.equals(this.energyMix, tariffDto.energyMix);
  }

   /**
   * Get energyMix
   * @return energyMix
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENERGY_MIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnergyMix getEnergyMix() {
    return energyMix;
  }


  @JsonProperty(JSON_PROPERTY_ENERGY_MIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnergyMix(EnergyMix energyMix) {
    this.energyMix = energyMix;
  }

  @Override
  public int hashCode() {
      return Objects.hash(id, currency, type, elements, countryCode, partyId, lastUpdated, tariffAltText, tariffAltUrl, minPrice, maxPrice, startDateTime, endDateTime, energyMix);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
      sb.append("class TariffDto {\n");
      sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
      sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
      sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
      sb.append("    tariffAltText: ").append(toIndentedString(tariffAltText)).append("\n");
    sb.append("    tariffAltUrl: ").append(toIndentedString(tariffAltUrl)).append("\n");
    sb.append("    minPrice: ").append(toIndentedString(minPrice)).append("\n");
    sb.append("    maxPrice: ").append(toIndentedString(maxPrice)).append("\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
    sb.append("    energyMix: ").append(toIndentedString(energyMix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
    AD_HOC_PAYMENT("AD_HOC_PAYMENT"),

    PROFILE_CHEAP("PROFILE_CHEAP"),

    PROFILE_FAST("PROFILE_FAST"),

    REGULAR("REGULAR"),

    PROFILE_GREEN("PROFILE_GREEN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

