/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.ClientInfoDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientInfoControllerApi
 */
@Ignore
public class ClientInfoControllerApiTest {

    private final ClientInfoControllerApi api = new ClientInfoControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHubClientInfoTest() {
        String countryCode = null;
        String partyId = null;
        ClientInfoDTO response = api.getHubClientInfo(countryCode, partyId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putHubClientInfoTest() {
        String countryCode = null;
        String partyId = null;
        api.putHubClientInfo(countryCode, partyId);

        // TODO: test validations
    }
    
}
