/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.CdrDTO;
import java.time.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoCdrControllerApi
 */
@Ignore
public class CpoCdrControllerApiTest {

    private final CpoCdrControllerApi api = new CpoCdrControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCdr1Test() {
        OffsetDateTime dateFrom = null;
        OffsetDateTime dateTo = null;
        Integer offset = null;
        Integer limit = null;
        List<CdrDTO> response = api.getCdr1(dateFrom, dateTo, offset, limit);

        // TODO: test validations
    }
    
}
