/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.CredentialsDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoCredentialsControllerApi
 */
@Ignore
public class CpoCredentialsControllerApiTest {

    private final CpoCredentialsControllerApi api = new CpoCredentialsControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCredentials1Test() {
        CredentialsDTO credentialsDTO = null;
        api.deleteCredentials1(credentialsDTO);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCredentials1Test() {
        CredentialsDTO response = api.getCredentials1();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCredentials1Test() {
        CredentialsDTO credentialsDTO = null;
        api.postCredentials1(credentialsDTO);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putCredentials1Test() {
        CredentialsDTO credentialsDTO = null;
        api.putCredentials1(credentialsDTO);

        // TODO: test validations
    }
    
}
