/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.ChargingProfileResponseDTO;
import com.extrawest.ocpp.client.model.SetChargingProfileRequestDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoChargingProfilesControllerApi
 */
@Ignore
public class CpoChargingProfilesControllerApiTest {

    private final CpoChargingProfilesControllerApi api = new CpoChargingProfilesControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteChargingProfileTest() {
        String sessionId = null;
        String responseUrl = null;
        ChargingProfileResponseDTO response = api.deleteChargingProfile(sessionId, responseUrl);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChargingProfileTest() {
        String sessionId = null;
        Integer duration = null;
        String responseUrl = null;
        ChargingProfileResponseDTO response = api.getChargingProfile(sessionId, duration, responseUrl);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putChargingProfile1Test() {
        String sessionId = null;
        SetChargingProfileRequestDTO setChargingProfileRequestDTO = null;
        ChargingProfileResponseDTO response = api.putChargingProfile1(sessionId, setChargingProfileRequestDTO);

        // TODO: test validations
    }
    
}
