/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.LocationDTO;
import java.time.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoLocationControllerApi
 */
@Ignore
public class CpoLocationControllerApiTest {

    private final CpoLocationControllerApi api = new CpoLocationControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocationEvseController1Test() {
        String locationId = null;
        String evseUid = null;
        String connectorId = null;
        Object response = api.getLocationEvseController1(locationId, evseUid, connectorId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocationsTest() {
        OffsetDateTime dateFrom = null;
        OffsetDateTime dateTo = null;
        Integer offset = null;
        Integer limit = null;
        List<LocationDTO> response = api.getLocations(dateFrom, dateTo, offset, limit);

        // TODO: test validations
    }
    
}
