/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.TokenDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoTokensControllerApi
 */
@Ignore
public class CpoTokensControllerApiTest {

    private final CpoTokensControllerApi api = new CpoTokensControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getToken1Test() {
        String countryCode = null;
        String partyId = null;
        String tokenUid = null;
        String type = null;
        TokenDTO response = api.getToken1(countryCode, partyId, tokenUid, type);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchTokenTest() {
        String countryCode = null;
        String partyId = null;
        String tokenUid = null;
        String type = null;
        TokenDTO tokenDTO = null;
        api.patchToken(countryCode, partyId, tokenUid, type, tokenDTO);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putTokenTest() {
        String countryCode = null;
        String partyId = null;
        String tokenUid = null;
        String type = null;
        TokenDTO tokenDTO = null;
        api.putToken(countryCode, partyId, tokenUid, type, tokenDTO);

        // TODO: test validations
    }
    
}
