/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.TariffDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmspTariffControllerApi
 */
@Ignore
public class EmspTariffControllerApiTest {

    private final EmspTariffControllerApi api = new EmspTariffControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTariffTest() {
        String countryCode = null;
        String partyId = null;
        String tariffId = null;
        api.deleteTariff(countryCode, partyId, tariffId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTariffTest() {
        String countryCode = null;
        String partyId = null;
        String tariffId = null;
        TariffDTO response = api.getTariff(countryCode, partyId, tariffId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveTariffTest() {
        String countryCode = null;
        String partyId = null;
        String tariffId = null;
        TariffDTO tariffDTO = null;
        api.saveTariff(countryCode, partyId, tariffId, tariffDTO);

        // TODO: test validations
    }
    
}
