/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.SessionDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmspSessionsControllerApi
 */
@Ignore
public class EmspSessionsControllerApiTest {

    private final EmspSessionsControllerApi api = new EmspSessionsControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSessionTest() {
        String countryCode = null;
        String partyId = null;
        String sessionId = null;
        SessionDTO response = api.getSession(countryCode, partyId, sessionId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchSessionTest() {
        String countryCode = null;
        String partyId = null;
        String sessionId = null;
        SessionDTO sessionDTO = null;
        api.patchSession(countryCode, partyId, sessionId, sessionDTO);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putSessionTest() {
        String countryCode = null;
        String partyId = null;
        String sessionId = null;
        SessionDTO sessionDTO = null;
        api.putSession(countryCode, partyId, sessionId, sessionDTO);

        // TODO: test validations
    }
    
}
