/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.AuthorizationInfoResponseDTO;
import com.extrawest.ocpp.client.model.LocationReferencesRequestDTO;
import java.time.OffsetDateTime;
import com.extrawest.ocpp.client.model.TokenDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmspTokenControllerApi
 */
@Ignore
public class EmspTokenControllerApiTest {

    private final EmspTokenControllerApi api = new EmspTokenControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokenTest() {
        OffsetDateTime dateFrom = null;
        OffsetDateTime dateTo = null;
        Integer offset = null;
        Integer limit = null;
        List<TokenDTO> response = api.getToken(dateFrom, dateTo, offset, limit);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postTokenTest() {
        String tokenUid = null;
        String type = null;
        LocationReferencesRequestDTO locationReferencesRequestDTO = null;
        AuthorizationInfoResponseDTO response = api.postToken(tokenUid, type, locationReferencesRequestDTO);

        // TODO: test validations
    }
    
}
