/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.LocationDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmspLocationControllerApi
 */
@Ignore
public class EmspLocationControllerApiTest {

    private final EmspLocationControllerApi api = new EmspLocationControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocationEvseControllerTest() {
        String countryCode = null;
        String partyId = null;
        String locationId = null;
        String evseUid = null;
        String connectorId = null;
        Object response = api.getLocationEvseController(countryCode, partyId, locationId, evseUid, connectorId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchLocationTest() {
        String countryCode = null;
        String partyId = null;
        String locationId = null;
        LocationDTO locationDTO = null;
        String evseUid = null;
        String connectorId = null;
        api.patchLocation(countryCode, partyId, locationId, locationDTO, evseUid, connectorId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pushLocationTest() {
        String countryCode = null;
        String partyId = null;
        String locationId = null;
        LocationDTO locationDTO = null;
        String evseUid = null;
        String connectorId = null;
        api.pushLocation(countryCode, partyId, locationId, locationDTO, evseUid, connectorId);

        // TODO: test validations
    }
    
}
