/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.api;

import com.extrawest.ocpp.client.model.AbstractProfileResult;
import com.extrawest.ocpp.client.model.ActiveChargingProfileRequestDTO;
import com.extrawest.ocpp.client.model.ResponseFormat;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmspChargingProfilesControllerApi
 */
@Ignore
public class EmspChargingProfilesControllerApiTest {

    private final EmspChargingProfilesControllerApi api = new EmspChargingProfilesControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postChargingProfileTest() {
        AbstractProfileResult abstractProfileResult = null;
        ResponseFormat response = api.postChargingProfile(abstractProfileResult);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putChargingProfileTest() {
        String sessionId = null;
        ActiveChargingProfileRequestDTO activeChargingProfileRequestDTO = null;
        ResponseFormat response = api.putChargingProfile(sessionId, activeChargingProfileRequestDTO);

        // TODO: test validations
    }
    
}
