/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.ChargingProfile;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ActiveChargingProfileRequestDTO
 */
public class ActiveChargingProfileRequestDTOTest {
    private final ActiveChargingProfileRequestDTO model = new ActiveChargingProfileRequestDTO();

    /**
     * Model tests for ActiveChargingProfileRequestDTO
     */
    @Test
    public void testActiveChargingProfileRequestDTO() {
        // TODO: test ActiveChargingProfileRequestDTO
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

    /**
     * Test the property 'chargingProfile'
     */
    @Test
    public void chargingProfileTest() {
        // TODO: test chargingProfile
    }

}
