/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.DisplayText;
import com.extrawest.ocpp.client.model.LocationReferences;
import com.extrawest.ocpp.client.model.Token;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuthorizationInfoResponseDTO
 */
public class AuthorizationInfoResponseDTOTest {
    private final AuthorizationInfoResponseDTO model = new AuthorizationInfoResponseDTO();

    /**
     * Model tests for AuthorizationInfoResponseDTO
     */
    @Test
    public void testAuthorizationInfoResponseDTO() {
        // TODO: test AuthorizationInfoResponseDTO
    }

    /**
     * Test the property 'allowed'
     */
    @Test
    public void allowedTest() {
        // TODO: test allowed
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'authorizationReference'
     */
    @Test
    public void authorizationReferenceTest() {
        // TODO: test authorizationReference
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

}
