/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.CdrLocation;
import com.extrawest.ocpp.client.model.CdrToken;
import com.extrawest.ocpp.client.model.ChargingPeriod;
import com.extrawest.ocpp.client.model.Price;
import com.extrawest.ocpp.client.model.SignedData;
import com.extrawest.ocpp.client.model.Tariff;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CdrDTO
 */
public class CdrDTOTest {
    private final CdrDTO model = new CdrDTO();

    /**
     * Model tests for CdrDTO
     */
    @Test
    public void testCdrDTO() {
        // TODO: test CdrDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'tariffs'
     */
    @Test
    public void tariffsTest() {
        // TODO: test tariffs
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'credit'
     */
    @Test
    public void creditTest() {
        // TODO: test credit
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'partyId'
     */
    @Test
    public void partyIdTest() {
        // TODO: test partyId
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

    /**
     * Test the property 'endDateTime'
     */
    @Test
    public void endDateTimeTest() {
        // TODO: test endDateTime
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'cdrToken'
     */
    @Test
    public void cdrTokenTest() {
        // TODO: test cdrToken
    }

    /**
     * Test the property 'authMethod'
     */
    @Test
    public void authMethodTest() {
        // TODO: test authMethod
    }

    /**
     * Test the property 'authorizationReference'
     */
    @Test
    public void authorizationReferenceTest() {
        // TODO: test authorizationReference
    }

    /**
     * Test the property 'cdrLocation'
     */
    @Test
    public void cdrLocationTest() {
        // TODO: test cdrLocation
    }

    /**
     * Test the property 'meterId'
     */
    @Test
    public void meterIdTest() {
        // TODO: test meterId
    }

    /**
     * Test the property 'chargingPeriods'
     */
    @Test
    public void chargingPeriodsTest() {
        // TODO: test chargingPeriods
    }

    /**
     * Test the property 'signedData'
     */
    @Test
    public void signedDataTest() {
        // TODO: test signedData
    }

    /**
     * Test the property 'totalCost'
     */
    @Test
    public void totalCostTest() {
        // TODO: test totalCost
    }

    /**
     * Test the property 'totalFixedCost'
     */
    @Test
    public void totalFixedCostTest() {
        // TODO: test totalFixedCost
    }

    /**
     * Test the property 'totalEnergy'
     */
    @Test
    public void totalEnergyTest() {
        // TODO: test totalEnergy
    }

    /**
     * Test the property 'totalEnergyCost'
     */
    @Test
    public void totalEnergyCostTest() {
        // TODO: test totalEnergyCost
    }

    /**
     * Test the property 'totalTime'
     */
    @Test
    public void totalTimeTest() {
        // TODO: test totalTime
    }

    /**
     * Test the property 'totalTimeCost'
     */
    @Test
    public void totalTimeCostTest() {
        // TODO: test totalTimeCost
    }

    /**
     * Test the property 'totalParkingTime'
     */
    @Test
    public void totalParkingTimeTest() {
        // TODO: test totalParkingTime
    }

    /**
     * Test the property 'totalParkingCost'
     */
    @Test
    public void totalParkingCostTest() {
        // TODO: test totalParkingCost
    }

    /**
     * Test the property 'totalReservationCost'
     */
    @Test
    public void totalReservationCostTest() {
        // TODO: test totalReservationCost
    }

    /**
     * Test the property 'invoiceReferenceId'
     */
    @Test
    public void invoiceReferenceIdTest() {
        // TODO: test invoiceReferenceId
    }

    /**
     * Test the property 'creditReferenceId'
     */
    @Test
    public void creditReferenceIdTest() {
        // TODO: test creditReferenceId
    }

    /**
     * Test the property 'homeChargingCompensation'
     */
    @Test
    public void homeChargingCompensationTest() {
        // TODO: test homeChargingCompensation
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
