/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ChargingPreferencesDTO
 */
public class ChargingPreferencesDTOTest {
    private final ChargingPreferencesDTO model = new ChargingPreferencesDTO();

    /**
     * Model tests for ChargingPreferencesDTO
     */
    @Test
    public void testChargingPreferencesDTO() {
        // TODO: test ChargingPreferencesDTO
    }

    /**
     * Test the property 'profileType'
     */
    @Test
    public void profileTypeTest() {
        // TODO: test profileType
    }

    /**
     * Test the property 'departureTime'
     */
    @Test
    public void departureTimeTest() {
        // TODO: test departureTime
    }

    /**
     * Test the property 'energyNeed'
     */
    @Test
    public void energyNeedTest() {
        // TODO: test energyNeed
    }

    /**
     * Test the property 'dischargeAllowed'
     */
    @Test
    public void dischargeAllowedTest() {
        // TODO: test dischargeAllowed
    }

}
