/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.ChargingProfilePeriod;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ChargingProfile
 */
public class ChargingProfileTest {
    private final ChargingProfile model = new ChargingProfile();

    /**
     * Model tests for ChargingProfile
     */
    @Test
    public void testChargingProfile() {
        // TODO: test ChargingProfile
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'chargingRateUnit'
     */
    @Test
    public void chargingRateUnitTest() {
        // TODO: test chargingRateUnit
    }

    /**
     * Test the property 'minChargingRate'
     */
    @Test
    public void minChargingRateTest() {
        // TODO: test minChargingRate
    }

    /**
     * Test the property 'chargingProfilePeriod'
     */
    @Test
    public void chargingProfilePeriodTest() {
        // TODO: test chargingProfilePeriod
    }

}
