/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Connector
 */
public class ConnectorTest {
    private final Connector model = new Connector();

    /**
     * Model tests for Connector
     */
    @Test
    public void testConnector() {
        // TODO: test Connector
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'standard'
     */
    @Test
    public void standardTest() {
        // TODO: test standard
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'powerType'
     */
    @Test
    public void powerTypeTest() {
        // TODO: test powerType
    }

    /**
     * Test the property 'maxVoltage'
     */
    @Test
    public void maxVoltageTest() {
        // TODO: test maxVoltage
    }

    /**
     * Test the property 'maxAmperage'
     */
    @Test
    public void maxAmperageTest() {
        // TODO: test maxAmperage
    }

    /**
     * Test the property 'maxElectricPower'
     */
    @Test
    public void maxElectricPowerTest() {
        // TODO: test maxElectricPower
    }

    /**
     * Test the property 'tariffIds'
     */
    @Test
    public void tariffIdsTest() {
        // TODO: test tariffIds
    }

    /**
     * Test the property 'termsAndConditions'
     */
    @Test
    public void termsAndConditionsTest() {
        // TODO: test termsAndConditions
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
