/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EnergyContract
 */
public class EnergyContractTest {
    private final EnergyContract model = new EnergyContract();

    /**
     * Model tests for EnergyContract
     */
    @Test
    public void testEnergyContract() {
        // TODO: test EnergyContract
    }

    /**
     * Test the property 'supplierName'
     */
    @Test
    public void supplierNameTest() {
        // TODO: test supplierName
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

}
