/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.EnergySource;
import com.extrawest.ocpp.client.model.EnvironmentalImpact;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EnergyMix
 */
public class EnergyMixTest {
    private final EnergyMix model = new EnergyMix();

    /**
     * Model tests for EnergyMix
     */
    @Test
    public void testEnergyMix() {
        // TODO: test EnergyMix
    }

    /**
     * Test the property 'isGreenEnergy'
     */
    @Test
    public void isGreenEnergyTest() {
        // TODO: test isGreenEnergy
    }

    /**
     * Test the property 'energySources'
     */
    @Test
    public void energySourcesTest() {
        // TODO: test energySources
    }

    /**
     * Test the property 'environImpact'
     */
    @Test
    public void environImpactTest() {
        // TODO: test environImpact
    }

    /**
     * Test the property 'supplierName'
     */
    @Test
    public void supplierNameTest() {
        // TODO: test supplierName
    }

    /**
     * Test the property 'energyProductName'
     */
    @Test
    public void energyProductNameTest() {
        // TODO: test energyProductName
    }

}
