/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.Connector;
import com.extrawest.ocpp.client.model.DisplayText;
import com.extrawest.ocpp.client.model.GeoLocation;
import com.extrawest.ocpp.client.model.Image;
import com.extrawest.ocpp.client.model.StatusSchedule;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EVSE
 */
public class EVSETest {
    private final EVSE model = new EVSE();

    /**
     * Model tests for EVSE
     */
    @Test
    public void testEVSE() {
        // TODO: test EVSE
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

    /**
     * Test the property 'evseId'
     */
    @Test
    public void evseIdTest() {
        // TODO: test evseId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusSchedule'
     */
    @Test
    public void statusScheduleTest() {
        // TODO: test statusSchedule
    }

    /**
     * Test the property 'capabilities'
     */
    @Test
    public void capabilitiesTest() {
        // TODO: test capabilities
    }

    /**
     * Test the property 'connectors'
     */
    @Test
    public void connectorsTest() {
        // TODO: test connectors
    }

    /**
     * Test the property 'floorLevel'
     */
    @Test
    public void floorLevelTest() {
        // TODO: test floorLevel
    }

    /**
     * Test the property 'coordinates'
     */
    @Test
    public void coordinatesTest() {
        // TODO: test coordinates
    }

    /**
     * Test the property 'physicalReference'
     */
    @Test
    public void physicalReferenceTest() {
        // TODO: test physicalReference
    }

    /**
     * Test the property 'directions'
     */
    @Test
    public void directionsTest() {
        // TODO: test directions
    }

    /**
     * Test the property 'parkingRestrictions'
     */
    @Test
    public void parkingRestrictionsTest() {
        // TODO: test parkingRestrictions
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
