/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.ExceptionalPeriod;
import com.extrawest.ocpp.client.model.RegularHours;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Hours
 */
public class HoursTest {
    private final Hours model = new Hours();

    /**
     * Model tests for Hours
     */
    @Test
    public void testHours() {
        // TODO: test Hours
    }

    /**
     * Test the property 'twentyfourseven'
     */
    @Test
    public void twentyfoursevenTest() {
        // TODO: test twentyfourseven
    }

    /**
     * Test the property 'regularHours'
     */
    @Test
    public void regularHoursTest() {
        // TODO: test regularHours
    }

    /**
     * Test the property 'exceptionalOpenings'
     */
    @Test
    public void exceptionalOpeningsTest() {
        // TODO: test exceptionalOpenings
    }

    /**
     * Test the property 'exceptionalClosings'
     */
    @Test
    public void exceptionalClosingsTest() {
        // TODO: test exceptionalClosings
    }

}
