/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.AdditionalGeoLocation;
import com.extrawest.ocpp.client.model.BusinessDetails;
import com.extrawest.ocpp.client.model.DisplayText;
import com.extrawest.ocpp.client.model.EVSE;
import com.extrawest.ocpp.client.model.EnergyMix;
import com.extrawest.ocpp.client.model.GeoLocation;
import com.extrawest.ocpp.client.model.Hours;
import com.extrawest.ocpp.client.model.Image;
import com.extrawest.ocpp.client.model.PublishTokenType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LocationDTO
 */
public class LocationDTOTest {
    private final LocationDTO model = new LocationDTO();

    /**
     * Model tests for LocationDTO
     */
    @Test
    public void testLocationDTO() {
        // TODO: test LocationDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'publish'
     */
    @Test
    public void publishTest() {
        // TODO: test publish
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'coordinates'
     */
    @Test
    public void coordinatesTest() {
        // TODO: test coordinates
    }

    /**
     * Test the property 'evses'
     */
    @Test
    public void evsesTest() {
        // TODO: test evses
    }

    /**
     * Test the property 'directions'
     */
    @Test
    public void directionsTest() {
        // TODO: test directions
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'subOperator'
     */
    @Test
    public void subOperatorTest() {
        // TODO: test subOperator
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'facilities'
     */
    @Test
    public void facilitiesTest() {
        // TODO: test facilities
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'partyId'
     */
    @Test
    public void partyIdTest() {
        // TODO: test partyId
    }

    /**
     * Test the property 'publishAllowedTo'
     */
    @Test
    public void publishAllowedToTest() {
        // TODO: test publishAllowedTo
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'relatedLocations'
     */
    @Test
    public void relatedLocationsTest() {
        // TODO: test relatedLocations
    }

    /**
     * Test the property 'parkingType'
     */
    @Test
    public void parkingTypeTest() {
        // TODO: test parkingType
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

    /**
     * Test the property 'openingTimes'
     */
    @Test
    public void openingTimesTest() {
        // TODO: test openingTimes
    }

    /**
     * Test the property 'chargingWhenClosed'
     */
    @Test
    public void chargingWhenClosedTest() {
        // TODO: test chargingWhenClosed
    }

    /**
     * Test the property 'energyMix'
     */
    @Test
    public void energyMixTest() {
        // TODO: test energyMix
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
