/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RegularHours
 */
public class RegularHoursTest {
    private final RegularHours model = new RegularHours();

    /**
     * Model tests for RegularHours
     */
    @Test
    public void testRegularHours() {
        // TODO: test RegularHours
    }

    /**
     * Test the property 'weekday'
     */
    @Test
    public void weekdayTest() {
        // TODO: test weekday
    }

    /**
     * Test the property 'periodBegin'
     */
    @Test
    public void periodBeginTest() {
        // TODO: test periodBegin
    }

    /**
     * Test the property 'periodEnd'
     */
    @Test
    public void periodEndTest() {
        // TODO: test periodEnd
    }

}
