/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.CdrToken;
import com.extrawest.ocpp.client.model.ChargingPeriod;
import com.extrawest.ocpp.client.model.Price;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SessionDTO
 */
public class SessionDTOTest {
    private final SessionDTO model = new SessionDTO();

    /**
     * Model tests for SessionDTO
     */
    @Test
    public void testSessionDTO() {
        // TODO: test SessionDTO
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'partyId'
     */
    @Test
    public void partyIdTest() {
        // TODO: test partyId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

    /**
     * Test the property 'endDateTime'
     */
    @Test
    public void endDateTimeTest() {
        // TODO: test endDateTime
    }

    /**
     * Test the property 'kwh'
     */
    @Test
    public void kwhTest() {
        // TODO: test kwh
    }

    /**
     * Test the property 'cdrToken'
     */
    @Test
    public void cdrTokenTest() {
        // TODO: test cdrToken
    }

    /**
     * Test the property 'authMethod'
     */
    @Test
    public void authMethodTest() {
        // TODO: test authMethod
    }

    /**
     * Test the property 'authorizationReference'
     */
    @Test
    public void authorizationReferenceTest() {
        // TODO: test authorizationReference
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'evseUid'
     */
    @Test
    public void evseUidTest() {
        // TODO: test evseUid
    }

    /**
     * Test the property 'connectorId'
     */
    @Test
    public void connectorIdTest() {
        // TODO: test connectorId
    }

    /**
     * Test the property 'meterId'
     */
    @Test
    public void meterIdTest() {
        // TODO: test meterId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'chargingPeriods'
     */
    @Test
    public void chargingPeriodsTest() {
        // TODO: test chargingPeriods
    }

    /**
     * Test the property 'totalCost'
     */
    @Test
    public void totalCostTest() {
        // TODO: test totalCost
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
