/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.ChargingProfile;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SetChargingProfileRequestDTO
 */
public class SetChargingProfileRequestDTOTest {
    private final SetChargingProfileRequestDTO model = new SetChargingProfileRequestDTO();

    /**
     * Model tests for SetChargingProfileRequestDTO
     */
    @Test
    public void testSetChargingProfileRequestDTO() {
        // TODO: test SetChargingProfileRequestDTO
    }

    /**
     * Test the property 'chargingProfile'
     */
    @Test
    public void chargingProfileTest() {
        // TODO: test chargingProfile
    }

    /**
     * Test the property 'responseUrl'
     */
    @Test
    public void responseUrlTest() {
        // TODO: test responseUrl
    }

}
