/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.SignedValue;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SignedData
 */
public class SignedDataTest {
    private final SignedData model = new SignedData();

    /**
     * Model tests for SignedData
     */
    @Test
    public void testSignedData() {
        // TODO: test SignedData
    }

    /**
     * Test the property 'encodingMethod'
     */
    @Test
    public void encodingMethodTest() {
        // TODO: test encodingMethod
    }

    /**
     * Test the property 'encodingMethodVersion'
     */
    @Test
    public void encodingMethodVersionTest() {
        // TODO: test encodingMethodVersion
    }

    /**
     * Test the property 'publicKey'
     */
    @Test
    public void publicKeyTest() {
        // TODO: test publicKey
    }

    /**
     * Test the property 'signedValues'
     */
    @Test
    public void signedValuesTest() {
        // TODO: test signedValues
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
