/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SignedValue
 */
public class SignedValueTest {
    private final SignedValue model = new SignedValue();

    /**
     * Model tests for SignedValue
     */
    @Test
    public void testSignedValue() {
        // TODO: test SignedValue
    }

    /**
     * Test the property 'plainDat'
     */
    @Test
    public void plainDatTest() {
        // TODO: test plainDat
    }

    /**
     * Test the property 'nature'
     */
    @Test
    public void natureTest() {
        // TODO: test nature
    }

    /**
     * Test the property 'plainData'
     */
    @Test
    public void plainDataTest() {
        // TODO: test plainData
    }

    /**
     * Test the property 'signedData'
     */
    @Test
    public void signedDataTest() {
        // TODO: test signedData
    }

}
