/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TariffRestrictions
 */
public class TariffRestrictionsTest {
    private final TariffRestrictions model = new TariffRestrictions();

    /**
     * Model tests for TariffRestrictions
     */
    @Test
    public void testTariffRestrictions() {
        // TODO: test TariffRestrictions
    }

    /**
     * Test the property 'reservation'
     */
    @Test
    public void reservationTest() {
        // TODO: test reservation
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'minKwh'
     */
    @Test
    public void minKwhTest() {
        // TODO: test minKwh
    }

    /**
     * Test the property 'maxKwh'
     */
    @Test
    public void maxKwhTest() {
        // TODO: test maxKwh
    }

    /**
     * Test the property 'minCurrent'
     */
    @Test
    public void minCurrentTest() {
        // TODO: test minCurrent
    }

    /**
     * Test the property 'maxCurrent'
     */
    @Test
    public void maxCurrentTest() {
        // TODO: test maxCurrent
    }

    /**
     * Test the property 'minPower'
     */
    @Test
    public void minPowerTest() {
        // TODO: test minPower
    }

    /**
     * Test the property 'maxPower'
     */
    @Test
    public void maxPowerTest() {
        // TODO: test maxPower
    }

    /**
     * Test the property 'minDuration'
     */
    @Test
    public void minDurationTest() {
        // TODO: test minDuration
    }

    /**
     * Test the property 'maxDuration'
     */
    @Test
    public void maxDurationTest() {
        // TODO: test maxDuration
    }

    /**
     * Test the property 'dayOfWeek'
     */
    @Test
    public void dayOfWeekTest() {
        // TODO: test dayOfWeek
    }

}
