/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.PriceComponent;
import com.extrawest.ocpp.client.model.TariffRestrictions;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TariffElement
 */
public class TariffElementTest {
    private final TariffElement model = new TariffElement();

    /**
     * Model tests for TariffElement
     */
    @Test
    public void testTariffElement() {
        // TODO: test TariffElement
    }

    /**
     * Test the property 'priceComponents'
     */
    @Test
    public void priceComponentsTest() {
        // TODO: test priceComponents
    }

    /**
     * Test the property 'restrictions'
     */
    @Test
    public void restrictionsTest() {
        // TODO: test restrictions
    }

}
