/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpp.client.model;

import com.extrawest.ocpp.client.model.DisplayText;
import com.extrawest.ocpp.client.model.EnergyMix;
import com.extrawest.ocpp.client.model.Price;
import com.extrawest.ocpp.client.model.TariffElement;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Tariff
 */
public class TariffTest {
    private final Tariff model = new Tariff();

    /**
     * Model tests for Tariff
     */
    @Test
    public void testTariff() {
        // TODO: test Tariff
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'partyId'
     */
    @Test
    public void partyIdTest() {
        // TODO: test partyId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'tariffAltText'
     */
    @Test
    public void tariffAltTextTest() {
        // TODO: test tariffAltText
    }

    /**
     * Test the property 'tariffAltUrl'
     */
    @Test
    public void tariffAltUrlTest() {
        // TODO: test tariffAltUrl
    }

    /**
     * Test the property 'minPrice'
     */
    @Test
    public void minPriceTest() {
        // TODO: test minPrice
    }

    /**
     * Test the property 'maxPrice'
     */
    @Test
    public void maxPriceTest() {
        // TODO: test maxPrice
    }

    /**
     * Test the property 'elements'
     */
    @Test
    public void elementsTest() {
        // TODO: test elements
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

    /**
     * Test the property 'endDateTime'
     */
    @Test
    public void endDateTimeTest() {
        // TODO: test endDateTime
    }

    /**
     * Test the property 'energyMix'
     */
    @Test
    public void energyMixTest() {
        // TODO: test energyMix
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
